### ISSUE TITLE
solve reverse interger challenge

### ISSUE THREAD

**Issue by FarshadJanmohammadi** [Code-Coterie-Team/Reverse-integer#1]
/**
 * Reverse Integer
 *
 * For given integer return an integer that is the reverse
 * ordering of numbers.
 *
 * Examples:
 * reverseInt(15) === 51
 * reverseInt(981) === 189
 * reverseInt(500) === 5
 * reverseInt(-15) === -51
 * reverseInt(-90) === -9
 */

**Comment by FarshadJanmohammadi** [comment]
Add dir="rtl" attribute to html tag that show result.

**Comment by arezooamiri** [comment]
Hi Farshad 
you told me I must change let to const  yesterday , I forgotten ask why? can you explain about it?
